In [2]:
# best_parameters = (X^T dot X)^-1 dot X^T dot y
# where y is the vector of target values with y_(1) to y_(m)
# best_parameters is the particular value that minimizes the cost function

In [13]:
import numpy as np
X = 2 * np.random.rand(100, 1) # create a 100 x 1 vector of randomized values
y = 4 + 3 * X + np.random.randn(100, 1) # plug in X vector into linear function, add some Gaussian noise
#Random data set created in y
print(y)

[[ 6.28559162]
 [ 7.93451263]
 [ 5.42506284]
 [ 4.97587977]
 [ 7.96063564]
 [ 5.8237346 ]
 [ 7.18265104]
 [ 6.1285051 ]
 [ 5.20125526]
 [ 6.02346014]
 [ 9.07744087]
 [ 4.79460387]
 [ 4.88880206]
 [ 4.33950829]
 [10.76702097]
 [ 8.17983432]
 [ 4.85015834]
 [ 6.37067459]
 [ 7.04356283]
 [ 9.55255677]
 [ 8.7496917 ]
 [ 4.38192496]
 [ 8.02355858]
 [ 6.42869614]
 [ 6.40376871]
 [ 7.79298894]
 [ 4.11223946]
 [ 5.78902626]
 [10.45806736]
 [ 9.0747574 ]
 [ 5.07125625]
 [ 8.34295797]
 [ 8.45169179]
 [ 4.44104151]
 [ 8.56032231]
 [ 4.90914778]
 [ 5.58063382]
 [ 9.66171707]
 [ 4.49385612]
 [ 8.60471512]
 [ 5.15126881]
 [ 5.70805616]
 [11.28339831]
 [ 4.63139539]
 [ 6.23453022]
 [ 7.24985896]
 [ 5.35170805]
 [ 9.66711858]
 [ 4.87563467]
 [ 2.46538013]
 [ 3.93637246]
 [ 8.32225886]
 [ 5.6031786 ]
 [ 7.08527524]
 [ 5.3534262 ]
 [ 8.90547761]
 [ 6.7631204 ]
 [ 6.07597728]
 [ 8.3750541 ]
 [ 8.49418866]
 [ 8.07144352]
 [ 8.09191067]
 [ 6.79217729]
 [ 6.2916415 ]
 [ 7.98917753]
 [ 7.13267336]
 [ 8.18750

In [17]:
X_b = np.c_[np.ones((100, 1)), X] # add a column of x0 = 1 to each instance
print(X_b)
theta_best = np.linalg.inv (X_b.T.dot(X_b)).dot(X_b.T).dot(y) # normal equation
# the normal equation returns parameters theta0, ..., thetaN that best predict the trend of the dataset

[[1.00000000e+00 5.48268415e-01]
 [1.00000000e+00 1.27485934e+00]
 [1.00000000e+00 7.55641557e-02]
 [1.00000000e+00 4.01488540e-04]
 [1.00000000e+00 1.55807942e+00]
 [1.00000000e+00 4.46054698e-01]
 [1.00000000e+00 1.16381848e+00]
 [1.00000000e+00 2.18951650e-01]
 [1.00000000e+00 4.78297604e-01]
 [1.00000000e+00 9.47580473e-02]
 [1.00000000e+00 1.09139668e+00]
 [1.00000000e+00 3.00342604e-01]
 [1.00000000e+00 3.64052887e-02]
 [1.00000000e+00 1.65692479e-01]
 [1.00000000e+00 1.83587321e+00]
 [1.00000000e+00 1.63247171e+00]
 [1.00000000e+00 4.85670768e-01]
 [1.00000000e+00 9.89834300e-01]
 [1.00000000e+00 9.54040797e-01]
 [1.00000000e+00 1.76185767e+00]
 [1.00000000e+00 1.46429992e+00]
 [1.00000000e+00 5.89902643e-01]
 [1.00000000e+00 1.59355237e+00]
 [1.00000000e+00 8.78504133e-01]
 [1.00000000e+00 7.20975112e-01]
 [1.00000000e+00 1.19227559e+00]
 [1.00000000e+00 2.77187233e-01]
 [1.00000000e+00 5.52854171e-01]
 [1.00000000e+00 1.91539642e+00]
 [1.00000000e+00 1.00798594e+00]
 [1.000000

In [18]:
# in this case, theta_best should be close to [4, 3] because of our equation, y = 4 + 3 * X
# the noise makes it impossible to recover exact parameters of the original function.
print(theta_best)

[[4.10138598]
 [2.92882723]]


In [ ]:
X_new = np.array([[0], [2]])
X_new_b = np.c_[np.ones((2, 1)), X_new] # add x0 = 1 to each instance