In [13]:
import numpy as np
from sklearn import datasets
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC

iris = datasets.load_iris()
X = iris["data"][:, (2, 3)] # select only (petal length, petal width) columns
y = (iris["target"] == 2).astype(np.float64) # is Iris-Virginica
iris["target"]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# Using the LinearSVC Class for Linear SVM Classifiers

In [9]:
svm_clf = Pipeline([
    ("scaler", StandardScaler()), # scale the features correctly to unit variance
    ("linear_svc", LinearSVC(C=1, loss="hinge")) 
    # C = penalty val. lower C = wider street, higher C = less margin violations 
    # hinge is the standard loss function for SVC
])
svm_clf.fit(X, y)

Pipeline(memory=None,
     steps=[('scaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('linear_svc', LinearSVC(C=1, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='hinge', max_iter=1000, multi_class='ovr',
     penalty='l2', random_state=None, tol=0.0001, verbose=0))])

In [49]:
svm_clf2.predict([[4.7, 1.7]]), svm_clf.predict([[4.8, 1.7]]), svm_clf.predict([[5.5, 1.7]])
# output: is not Iris Virginica, is Iris Virginica, is Iris Virginica

(array([0.]), array([1.]), array([1.]))

# Training Linear SVMs with Stochastic Gradient Descent

In [37]:
from sklearn.linear_model import SGDClassifier

C = 1 # original C hyperparameter will need to be converted in SGDClassifier
m = 59
svm_clf2 = Pipeline([
    ("scaler", StandardScaler()), # scale the features correctly to unit variance
    ("linear_svc", SGDClassifier(loss="hinge", alpha=1/(m*C), max_iter=50, random_state=42)) 
    # C = penalty val. lower C = wider street, higher C = less margin violations 
    # hinge is the standard loss function for SVC
])
svm_clf2.fit(X, y)

Pipeline(memory=None,
     steps=[('scaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('linear_svc', SGDClassifier(alpha=0.01694915254237288, average=False, class_weight=None,
       epsilon=0.1, eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='hinge', max_iter=50, n_iter=None,
       n_jobs=1, penalty='l2', power_t=0.5, random_state=42, shuffle=True,
       tol=None, verbose=0, warm_start=False))])

In [50]:
svm_clf2.predict([[4.7, 1.7]]), svm_clf2.predict([[4.8, 1.7]]), svm_clf.predict([[5.5, 1.7]])

(array([0.]), array([1.]), array([1.]))