In [3]:
import numpy as np
m = 100
X = 6 * np.random.rand(m, 1) - 3 # data set with values in [-3, 3]
y = 0.5 * X ** 2 + X + 2 + np.random.rand(m, 1) #polynomial data set with some gaussian noise
X

array([[ 0.48735496],
       [ 1.96916113],
       [ 1.79378767],
       [ 1.19959048],
       [ 0.33932454],
       [ 1.8589538 ],
       [ 2.36609279],
       [ 2.72678933],
       [ 1.55892416],
       [-2.03494842],
       [ 0.8759396 ],
       [ 0.67032991],
       [ 0.7695369 ],
       [ 0.61278642],
       [ 1.3099837 ],
       [-1.78962594],
       [-2.17940505],
       [-0.6282602 ],
       [ 2.79568401],
       [-1.97631499],
       [ 2.68489977],
       [-1.05893321],
       [-2.9374342 ],
       [ 1.59479312],
       [-0.27279003],
       [ 1.92642428],
       [-0.31846051],
       [ 0.74216421],
       [-0.45335922],
       [-1.1310276 ],
       [ 0.68969577],
       [ 2.80515636],
       [ 2.31179243],
       [ 1.44901187],
       [-1.21829925],
       [ 1.54657651],
       [ 0.81692154],
       [ 0.48862789],
       [-0.74083133],
       [-0.5383427 ],
       [-2.74097057],
       [ 2.95421351],
       [ 1.24187646],
       [-0.40250929],
       [-2.65189845],
       [-0

In [4]:
import matplotlib.pyplot as plt
plt.plot(X, y, "b.") #plot the x-y graph with blue circle points
plt.axis([-3, 3, 1, 10]) #x axis from -3 to 3, y axis from 1 to 10
plt.show()

<Figure size 640x480 with 1 Axes>

In [5]:
from sklearn.preprocessing import PolynomialFeatures
poly_features = PolynomialFeatures(degree=2, include_bias=False) #class to transform polynomial into one of degree 2
X_poly = poly_features.fit_transform(X) # takes the each value in vector X as the input x, calculates X^2 and X to make quadratic
X[0]
X_poly[0] # == (X, X^2)

array([0.48735496, 0.23751486])

In [29]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression() # make a new linear regression model
lin_reg.fit(X_poly, y) # try to find the best fitting coefficients when training set X_poly is trained against target vector y
lin_reg.intercept_, lin_reg.coef_
# prints out the y intercept of the best-fit function, and coefficients for (X, X^2)

(array([2.46234118]), array([[1.0126007 , 0.50183773]]))

In [1]:
# thus, it predicts the equation (in this particular case) to be y = 0.5018x^2 + 1.0126x + 2.462
# which is close to the original, y = 0.5x^2 + x + 2, considering there was gaussian noise added